[package]
name = "redo-bare"
version = "0.1.0"
authors = ["Johann Lee <me@qinka.pro>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
redo-cpu = { path = "../redo-cpu" }